### ISSUE TITLE
question#160 answer needs to be revisited

### ISSUE THREAD

**Issue by MeowPiang** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers#22]
Isn't AWS CloudTrail the service to use for tracking resource changes  using the API calls history? 
Amazon CloudWatch is the service to check vulnerability. 
Please revisit the answer of this question. Much appreciation.

**Comment by danieldanielecki** [comment]
Absolutely. Confirmed by Google + Copilot + https://github.com/kananinirav/AWS-Certified-Cloud-Practitioner-Notes/blob/master/practice-exam/practice-exam-4.md, fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/commit/d54d5a49e2d434fc3875ad6671e5b91d344d6823.

<img width="1092" alt="Screenshot 2024-07-08 at 15 07 52" src="https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/assets/12736263/e71721bc-3a4d-4a67-9e23-3378742d32b9">

<img width="1047" alt="Screenshot 2024-07-08 at 15 09 28" src="https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C02-Practice-Tests-Exams-Questions-Answers/assets/12736263/25abf380-75a9-49b2-ae55-7e486806d2be">

**Comment by MeowPiang** [comment]
Thanks for the confirmation.
